version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: cypress
    versions:
    - 6.3.0
    - 6.4.0
    - 6.5.0
    - 6.6.0
    - 6.7.1
    - 6.8.0
    - 7.0.0
    - 7.0.1
    - 7.1.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@cypress/code-coverage"
    versions:
    - 3.9.2
    - 3.9.3
    - 3.9.4
  - dependency-name: react-scripts
    versions:
    - 4.0.2
  - dependency-name: start-server-and-test
    versions:
    - 1.11.7
    - 1.12.0
  - dependency-name: node-notifier
    versions:
    - 8.0.1
